---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  # Decryption configuration starts here
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
